---
AllCops:
  TargetChefVersion: 16.latest
  Exclude:
    - Rakefile
    - Berksfile
    - Vagrantfile
    - Thorfile
    # - Gemfile
    - ".kitchen/*"
Chef/Modernize/FoodcriticComments:
  Enabled: true
Chef/Style/CopyrightCommentFormat:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
