AllCops:
  Exclude:
    - Rakefile
    - Berksfile
    - Vagrantfile
    - Thorfile
    - Gemfile
    - ".kitchen/*"
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 75
CyclomaticComplexity:
  Enabled: false
GuardClause:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 50
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
AbcSize:
  Enabled: false
