name: Run tests

on: [push, pull_request]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Prepare
        run: |
          bundle install
      - name: Run Rubocop
        run: |
          rake rubocop
      - name: Run Foodcritic
        run: |
          rake foodcritic
