name: Run tests

on: [push, pull_request]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Prepare
        run: |
          bundle config path vendor/bundle
          bundle config set without 'development integration'
          bundle install --jobs 4 --retry 3
      - name: Run ChefStyle
        run: |
          rubocop -r chefstyle --format offenses
      - name: Run Foodcritic
        run: |
          rake foodcritic
      - name: Run Rubocop
        run: |
          rake rubocop
